nelmio_api_doc:
    documentation:
        info:
            title: Restaurant API
            description: Documentation de l'API du projet Restaurant
            version: 1.0.0
        components:
            securitySchemes:
                X-AUTH-TOKEN:
                    type: apiKey
                    in: header
                    name: X-AUTH-TOKEN
        security:
            - X-AUTH-TOKEN: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
